version: "3.1"

services:
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ${BASE_PATH}:/var/www/html
